# Generated by Django 2.1 on 2019-10-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name': 'телефон', 'verbose_name_plural': 'телефоны'},
        ),
        migrations.AddField(
            model_name='phone',
            name='status',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='geobase',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Геобаз'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='profession',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Профессия'),
        ),
    ]
