# Generated by Django 2.1 on 2019-10-22 13:39

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
        ('main', '0002_auto_20191022_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Texts',
            fields=[
                ('preferences_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='preferences.Preferences')),
                ('start_message', models.TextField(default='-', verbose_name='Приветсвенное сообщение')),
                ('main_message', models.TextField(default='-', verbose_name='Сообщение для ввода номера')),
            ],
            bases=('preferences.preferences',),
            managers=[
                ('singleton', django.db.models.manager.Manager()),
            ],
        ),
    ]
