# Generated by Django 2.1 on 2019-10-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_texts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='texts',
            options={'verbose_name': 'текст', 'verbose_name_plural': 'тексты'},
        ),
        migrations.AddField(
            model_name='texts',
            name='no_result_message',
            field=models.TextField(default='-', verbose_name='Сообщение не найдено результатов'),
        ),
        migrations.AddField(
            model_name='texts',
            name='result_message',
            field=models.TextField(default='-', verbose_name='Сообщение с результатом'),
        ),
    ]
