# Generated by Django 2.1 on 2019-10-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191023_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='geobase',
            field=models.CharField(blank=True, default='-', max_length=256, null=True, verbose_name='Геобаз'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='name',
            field=models.CharField(blank=True, default='-', max_length=256, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='profession',
            field=models.CharField(blank=True, default='-', max_length=256, null=True, verbose_name='Профессия'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='status',
            field=models.CharField(blank=True, default='-', max_length=256, null=True, verbose_name='Статус'),
        ),
    ]
