# Generated by Django 2.1 on 2019-10-24 16:53

import datetime
from django.db import migrations, models
import django.utils.timezone
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AddField(
            model_name='post',
            name='amount_of_receivers',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество пользователей, получивших пост'),
        ),
        migrations.AddField(
            model_name='post',
            name='button_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка кнопки'),
        ),
        migrations.AddField(
            model_name='post',
            name='button_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания (часовой пояс UTC)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=main.models.Image(blank=True, null=True, upload_to=main.models.Image.get_path, validators=[main.models.Image.validate_image], verbose_name='Изображение снизу (до 1МБ)'),
        ),
        migrations.AddField(
            model_name='post',
            name='postpone',
            field=models.BooleanField(default=False, verbose_name='Отложить'),
        ),
        migrations.AddField(
            model_name='post',
            name='postpone_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 1, 0, 0), verbose_name='Время публикации (часовой пояс UTC)'),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('postponed', 'Отложен'), ('queue', 'В очереди'), ('process', 'Рассылается'), ('done', 'Разослан')], default='created', max_length=9, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default='', max_length=4000, verbose_name='Форматированный текст'),
            preserve_default=False,
        ),
    ]
