# Generated by Django 2.1 on 2019-10-24 16:57

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20191024_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания (часовой пояс UTC)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=main.models.Image(blank=True, null=True, upload_to=main.models.Image.get_path, validators=[main.models.Image.validate_image], verbose_name='Изображение снизу (до 1МБ)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=4000, null=True, verbose_name='Форматированный текст'),
        ),
    ]
