# Generated by Django 2.1 on 2019-10-24 16:57

import datetime
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20191024_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=main.models.Image(blank=True, null=True, upload_to=main.models.Image.get_path, validators=[main.models.Image.validate_image], verbose_name='Изображение снизу (до 1МБ)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postpone',
            field=models.BooleanField(default=False, null=True, verbose_name='Отложить'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postpone_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 1, 0, 0), null=True, verbose_name='Время публикации (часовой пояс UTC)'),
        ),
    ]
