# Generated by Django 2.1 on 2019-10-24 17:06

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20191024_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='button_link',
        ),
        migrations.RemoveField(
            model_name='post',
            name='button_title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='postpone',
        ),
        migrations.RemoveField(
            model_name='post',
            name='postpone_time',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=main.models.Image(blank=True, null=True, upload_to=main.models.Image.get_path, validators=[main.models.Image.validate_image], verbose_name='Изображение снизу (до 1МБ)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('queue', 'В очереди'), ('process', 'Рассылается'), ('done', 'Разослан')], default='created', max_length=9, verbose_name='Статус'),
        ),
    ]
