# Generated by Django 2.1 on 2019-10-26 11:20

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20191024_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='texts',
            options={'verbose_name': 'список', 'verbose_name_plural': 'списки'},
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone',
            field=models.CharField(help_text='Без "+".', max_length=256, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=main.models.Image(blank=True, null=True, upload_to=main.models.Image.get_path, validators=[main.models.Image.validate_image], verbose_name='Изображение снизу (до 1МБ)'),
        ),
        migrations.AlterField(
            model_name='texts',
            name='main_message',
            field=models.TextField(default='-', verbose_name='Ввод номера'),
        ),
        migrations.AlterField(
            model_name='texts',
            name='no_result_message',
            field=models.TextField(default='-', verbose_name='Пусто'),
        ),
        migrations.AlterField(
            model_name='texts',
            name='result_message',
            field=models.TextField(default='-', verbose_name='Результат'),
        ),
        migrations.AlterField(
            model_name='texts',
            name='start_message',
            field=models.TextField(default='-', verbose_name='Приветствие'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='@username'),
        ),
    ]
