# Generated by Django 2.1 on 2019-10-26 12:38

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20191026_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'пост', 'verbose_name_plural': 'посты'},
        ),
        migrations.AlterField(
            model_name='phone',
            name='geobase',
            field=models.CharField(default='-', max_length=256, verbose_name='Геобаз'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='name',
            field=models.CharField(default='-', max_length=256, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone',
            field=models.CharField(help_text='Без "+"', max_length=256, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='profession',
            field=models.CharField(default='-', max_length=256, verbose_name='Профессия'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='status',
            field=models.CharField(default='-', max_length=256, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='post',
            name='amount_of_receivers',
            field=models.IntegerField(blank=True, null=True, verbose_name='Получателей'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания, UTC'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=main.models.Image(blank=True, null=True, upload_to=main.models.Image.get_path, validators=[main.models.Image.validate_image], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=4000, null=True, verbose_name='Текст'),
        ),
    ]
